using System;
using System.Collections.Generic;

namespace BetterBTD.Services;

public sealed partial class LocalizationService
{
    private static Dictionary<string, string> BuildZhCnStartResources() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["Start.HeroImageTitle"] = "游戏展示图",
        ["Start.HeroImageHint"] = "（占位图，后续可替换为实际大图）",
        ["Start.ActionPanelTitle"] = "核心功能",
        ["Start.ActionPanelDescription"] = "保持简洁直达，方便在游戏窗口旁快速操作。",
        ["Start.LaunchGame"] = "启动游戏",
        ["Start.LaunchCapture"] = "启动截图器",
        ["Start.StopCapture"] = "停止截图器",
        ["Start.Hint"] = "提示：当前仅完成 UI 设计，按钮逻辑后续接入。",
        ["Start.BannerTitle"] = "BetterBTD",
        ["Start.BannerSubtitle"] = "更好的自动化体验，简洁且可扩展",
        ["Start.BannerLinkText"] = "点击查看文档与教程",
        ["Start.ChangeBanner"] = "更换背景图片",
        ["Start.ResetBanner"] = "恢复默认图片",
        ["Start.CaptureCardTitle"] = "截图器启动",
        ["Start.CaptureCardDescription"] = "截图器启动后才能使用多数自动化功能。",
        ["Start.CaptureModeTitle"] = "截图模式",
        ["Start.CaptureModeDescription"] = "推荐选择 BitBlt，问题较少。",
        ["Start.TriggerIntervalTitle"] = "触发器间隔（毫秒）",
        ["Start.TriggerIntervalDescription"] = "默认 50ms，普通用户不建议调整。",
        ["Start.CaptureTestTitle"] = "测试图像捕获",
        ["Start.CaptureTestDescription"] = "测试几种截图模式的效果。",
        ["Start.CaptureTestButtonText"] = "测试图像捕获",
        ["Start.ManualPickWindowTitle"] = "手动选择窗口",
        ["Start.ManualPickWindowDescription"] = "找不到游戏窗口时使用。",
        ["Start.ManualPickWindowButtonText"] = "选择捕获窗口",
        ["Start.AutoFixWin11Title"] = "自动关闭 Win11 窗口优化",
        ["Start.AutoFixWin11Description"] = "修改后重启游戏生效。",
        ["Start.ManualSettings"] = "手动设置",
        ["Start.LinkedStartTitle"] = "同时启动游戏",
        ["Start.LinkedStartDescription"] = "启动截图器时如果游戏未启动，将自动尝试启动。",
        ["Start.InstallPathTitle"] = "游戏安装位置",
        ["Start.InstallPathDescription"] = "联动启动会使用该路径。",
        ["Start.StartArgsTitle"] = "启动参数",
        ["Start.StartArgsDescription"] = "不清楚参数用途时建议保持为空。",
        ["Start.OpenDoc"] = "打开文档",
        ["Start.AutoEnterGameTitle"] = "自动进入游戏",
        ["Start.AutoEnterGameDescription"] = "游戏启动后自动执行进入流程。",
        ["Start.StartWithCmdTitle"] = "使用 CMD 启动游戏",
        ["Start.StartWithCmdDescription"] = "遇到启动兼容问题时可尝试开启。",
        ["Start.RecordGameTimeTitle"] = "记录游戏时间",
        ["Start.RecordGameTimeDescription"] = "启动后同步记录时长。",
        ["Start.Browse"] = "浏览"
    };

    private static Dictionary<string, string> BuildEnUsStartResources() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["Start.HeroImageTitle"] = "Game Hero Image",
        ["Start.HeroImageHint"] = "(placeholder for future artwork)",
        ["Start.ActionPanelTitle"] = "Core Actions",
        ["Start.ActionPanelDescription"] = "Keep key actions simple beside the game window.",
        ["Start.LaunchGame"] = "Launch Game",
        ["Start.LaunchCapture"] = "Launch Capturer",
        ["Start.StopCapture"] = "Stop Capturer",
        ["Start.Hint"] = "Note: this step only provides UI mockup without runtime logic.",
        ["Start.BannerTitle"] = "BetterBTD",
        ["Start.BannerSubtitle"] = "A better automation experience, minimal and extensible",
        ["Start.BannerLinkText"] = "Open docs and tutorials",
        ["Start.ChangeBanner"] = "Change banner image",
        ["Start.ResetBanner"] = "Reset default image",
        ["Start.CaptureCardTitle"] = "Capturer Startup",
        ["Start.CaptureCardDescription"] = "Most automation features require the capturer to be running.",
        ["Start.CaptureModeTitle"] = "Capture Mode",
        ["Start.CaptureModeDescription"] = "BitBlt is recommended for better compatibility.",
        ["Start.TriggerIntervalTitle"] = "Trigger Interval (ms)",
        ["Start.TriggerIntervalDescription"] = "Default is 50ms; regular users should keep this value.",
        ["Start.CaptureTestTitle"] = "Capture Test",
        ["Start.CaptureTestDescription"] = "Test capture quality in several modes.",
        ["Start.CaptureTestButtonText"] = "Test Capture",
        ["Start.ManualPickWindowTitle"] = "Manual Window Pick",
        ["Start.ManualPickWindowDescription"] = "Use this if the game window is not found.",
        ["Start.ManualPickWindowButtonText"] = "Pick Capture Window",
        ["Start.AutoFixWin11Title"] = "Auto Fix Win11 Window Optimization",
        ["Start.AutoFixWin11Description"] = "Restart game after applying this setting.",
        ["Start.ManualSettings"] = "Manual Setting",
        ["Start.LinkedStartTitle"] = "Launch Game Together",
        ["Start.LinkedStartDescription"] = "When starting capturer, launch game automatically if needed.",
        ["Start.InstallPathTitle"] = "Game Install Path",
        ["Start.InstallPathDescription"] = "Linked startup uses this path.",
        ["Start.StartArgsTitle"] = "Startup Arguments",
        ["Start.StartArgsDescription"] = "Leave empty if you are unsure.",
        ["Start.OpenDoc"] = "Open doc",
        ["Start.AutoEnterGameTitle"] = "Auto Enter Game",
        ["Start.AutoEnterGameDescription"] = "Run enter-game steps automatically after launch.",
        ["Start.StartWithCmdTitle"] = "Start Game with CMD",
        ["Start.StartWithCmdDescription"] = "Enable this when startup compatibility issues occur.",
        ["Start.RecordGameTimeTitle"] = "Record Game Time",
        ["Start.RecordGameTimeDescription"] = "Track playtime after launch.",
        ["Start.Browse"] = "Browse"
    };
}
